### ISSUE TITLE
Incorrect Setup Import

### ISSUE THREAD

**Issue by jdgme** [Rcasco/odometer-ngx#1]
**Note: for support questions, please use one of these channels:** 

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Reporting a bug

* **What is the current behavior?**
Following the setup steps in the documentation results in the following build failure:

Module not found: Error: Can't resolve 'tm-ng-odometer'

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

1. Add odometer-ngx at command line using: npm install odometer-ngx --save
2. Add to app.module.ts: import { TmNgOdometerModule } from 'tm-ng-odometer';
3. Add to app.module.ts @NgModule imports array: TmNgOdometerModule

* **What is the expected behavior?**

Project builds without error.

* **What is the motivation / use case for changing the behavior?**

The project doesn't function following the current Setup instructions.

* **Please tell us about your environment:**

- Angular version: 15.2.9
- Node version 18.17.0
- npm version 9.6.7
- OS win32 x64
- Browser: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
The documentation simply needs to be corrected to import from the correct location:

`import { TmNgOdometerModule } from 'odometer-ngx';`

**Comment by Rcasco** [comment]
Thanks for pointing this out. I have updated it.
